export const selectors = {
  matchList: {
    matchRow: "li.table-main__tournamentLiContent[data-event-id]",
    matchInfo: "ul.table-main__matchInfo",
    matchTime: '[data-live-cell="time"]',
    matchLink: 'a[data-live-cell="matchlink"]',
    participants: "a.table-main__participants",
    homeTeam: ".table-main__participantHome p",
    awayTeam: ".table-main__participantAway p, .table-main__participantAway div.particiantWidthMobile",
    teamLogos: "img.table-main__participantLogo",
    score: '[data-live-cell="score"]',
    odds: ".table-main__odds[data-oid]",
    leagueContainer: "ul.leagues-list",
    leagueHeader: ".table-main__tournamentNavLi",
    leagueName: ".table-main__leaguesNames",
    countryFlag: ".table-main__countryFlags",
  },
  h2h: {
    component: "#H2HComponent",
    title: "#H2HComponent .componentHeader",
    homeWins: "#H2HComponent .totalWinHome",
    draws: "#H2HComponent .totalDraw",
    awayWins: "#H2HComponent .totalWinAway",
    homePercent: "#H2HComponent .percentage-bar__home",
    drawPercent: "#H2HComponent .percentage-bar__draw",
    awayPercent: "#H2HComponent .percentage-bar__away",
    rows: "#mutual_div .head-to-head__row",
  },
  recentResults: {
    component: "#lastResultsComponent",
    homeResults: "#match-results-home",
    awayResults: "#match-results-away",
    title: ".last-results__title .componentHeader",
    rows: ".head-to-head__row",
    date: ".head-to-head__date .mobileHidden, .head-to-head__date",
    link: "a.table-main__participants",
    homeTeam: ".table-main__participantHome p",
    awayTeam: ".table-main__participantAway p, .table-main__participantAway div.particiantWidthMobile",
    score: ".mainResult.last-results__form-results span, .table-main__result, .mainResult span",
    odds: ".last-results__odds-align .table-main__odd, .table-main__odd",
    form: ".last-results__form-results",
  },
  standings: {
    ajaxLink: 'a[href*="/standings/"][href*="table=table"]',
    submenuLink: ".standings__submenu-a",
    table: "#table-type-1.stats-table, .stats-table",
    rows: "#table-type-1 tbody tr, .stats-table tbody tr",
    rank: '.rank.col_rank, [data-type="rank"]',
    team: '.participant_name.col_name, [data-type="participant_name"], [data-type="team"]',
    played: '.matches, .matches_played, [data-type="matches"]',
    wins: '.wins_regular, [data-type="wins_regular"], [data-type="wins"]',
    draws: '.draws, [data-type="draws"]',
    losses: '.losses_regular, [data-type="losses_regular"], [data-type="losses"]',
    goals: '.goals, [data-type="goals"]',
    goalDifference: '.goals_for_against_diff, [data-type="goals_for_against_diff"], [data-type="goal_difference"]',
    points: '.points, [data-type="points"]',
    form: '.form, [data-type="form"]',
  },
  teamPage: {
    title: "h1",
    tabs: ".list-tabs a",
    table: "table.table-main.teaminfo",
    tournamentRows: "table.teaminfo tbody tr[data-tsid]",
    matchRows: "table.teaminfo tbody tr[data-ttid]:not([data-tsid])",
    formIcon: ".table-main__formicon i",
    tournamentLink: ".table-main__tournament",
    detailsLink: 'a[href*="/football/"]',
    dateCell: "td.h-text-right.h-text-no-wrap",
    filter: 'select[onchange*="teaminfo_change_matches"]',
  },
} as const;
